import { useState, useEffect } from 'react';
import Header from './components/Header';
import QuoteForm from './components/QuoteForm';
import QuoteHistory from './components/QuoteHistory';
import LoginModal from './components/LoginModal';
import { supabase } from './lib/supabase';

function App() {
  const [user, setUser] = useState(null);
  const [quotes, setQuotes] = useState([]);
  const [showLogin, setShowLogin] = useState(false);
  const [todaysQuotes, setTodaysQuotes] = useState(0);

  useEffect(() => {
    // Check current user session
    const getSession = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      setUser(session?.user || null);
      if (session?.user) {
        await loadUserQuotes(session.user.id);
        await checkTodaysQuotes(session.user.id);
      }
    };

    getSession();

    // Listen for auth changes
    const { data: { subscription } } = supabase.auth.onAuthStateChange(
      async (event, session) => {
        setUser(session?.user || null);
        if (session?.user) {
          await loadUserQuotes(session.user.id);
          await checkTodaysQuotes(session.user.id);
        } else {
          setQuotes([]);
          setTodaysQuotes(0);
        }
      }
    );

    return () => subscription.unsubscribe();
  }, []);

  const loadUserQuotes = async (userId) => {
    const { data, error } = await supabase
      .from('quotes')
      .select('*')
      .eq('user_id', userId)
      .order('created_at', { ascending: false });

    if (!error && data) {
      setQuotes(data);
    }
  };

  const checkTodaysQuotes = async (userId) => {
    const today = new Date().toISOString().split('T')[0];
    const { data, error } = await supabase
      .from('quotes')
      .select('id')
      .eq('user_id', userId)
      .gte('created_at', `${today}T00:00:00`)
      .lte('created_at', `${today}T23:59:59`);

    if (!error) {
      setTodaysQuotes(data.length);
    }
  };

  const handleNewQuote = (quote) => {
    setQuotes(prev => [quote, ...prev]);
    setTodaysQuotes(prev => prev + 1);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
      <Header 
        user={user} 
        onLoginClick={() => setShowLogin(true)}
        onLogout={async () => {
          await supabase.auth.signOut();
        }}
      />
      
      <main className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <h1 className="text-4xl font-bold text-gray-800 mb-4">
              AI Quotes Generator
            </h1>
            <p className="text-lg text-gray-600">
              Enter a keyword and get inspiring quotes generated by AI
            </p>
          </div>

          {user && (
            <div className="bg-white rounded-lg shadow-md p-6 mb-8">
              <div className="flex justify-between items-center mb-4">
                <h2 className="text-xl font-semibold">Daily Usage</h2>
                <span className={`px-3 py-1 rounded-full text-sm font-medium ${
                  todaysQuotes < 5 ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'
                }`}>
                  {todaysQuotes}/5 quotes used today
                </span>
              </div>
              {todaysQuotes >= 5 && (
                <p className="text-yellow-600 text-sm">
                  You've reached your daily limit. Generate unlimited quotes by upgrading.
                </p>
              )}
            </div>
          )}

          <QuoteForm 
            user={user}
            todaysQuotes={todaysQuotes}
            onNewQuote={handleNewQuote}
            onLoginRequired={() => setShowLogin(true)}
          />

          {user && quotes.length > 0 && (
            <QuoteHistory quotes={quotes} />
          )}
        </div>
      </main>

      {showLogin && (
        <LoginModal onClose={() => setShowLogin(false)} />
      )}
    </div>
  );
}

export default App;
